### ISSUE TITLE
Update README for New Comers

### ISSUE THREAD

**Issue by channprj** [channprj/us-twitter-shortcuts#1]
## Summary

- Add install button
- Add screenshots or simple gifs
- Add "How to use" sections

**Comment by mk-singhal** [comment]
Hi @channprj ,
I would like to work on this..

**Comment by channprj** [comment]
@devTeaa Yes. This is UserScript project.

**Comment by channprj** [comment]
@mk-singhal Thank you for your help. PR is always open. 🤩

**Comment by mk-singhal** [comment]
Hi @channprj check the pr #2  .

**Comment by channprj** [comment]
Thank you! fixed #2
